### ISSUE TITLE
Orbiter touching the part cooling fan

### ISSUE THREAD

**Issue by Lwinz** [sneakytreesnake/StealthOrbiter#10]
As title, orbiter touching the part cooling fan and press when tighten the front screw

**Comment by sneakytreesnake** [comment]
Correct. This is “intended”.

I can’t move the orbiter without putting a bend/kink in the filament path, or breaking compatibility with the rest of the stealthburner parts.

As a result, the orbiter will touch the back of the fan. Since this doesn’t negatively affect anything, I considered this option better than linking the filament path.

**Comment by Lwinz** [comment]
I will try reassembling it. Thanks for the reply
