### ISSUE TITLE
Print orientation question

### ISSUE THREAD

**Issue by DreamingRaven** [sneakytreesnake/StealthOrbiter#6]
Hey quick question, the readme says "Print the mount with the front face on the bed (so the hold for the ball bearing is printed vertically). Use standard Voron print settings."

However I am unsure what the front face is on this model, 
![orientation](https://user-images.githubusercontent.com/10534713/227002344-0ca08851-987f-4dec-a5bb-77f33d5b7653.png)

Is it this orientation? I assume I will need supports no matter which orientation I use.

Thanks, sorry for the relatively silly question, there are just two orientations it could be to keep the ball holder vertical if you don't know which side is the front.

**Comment by sneakytreesnake** [comment]
Hello, I plan on updating the documentation soon to include printing instructions....

.. but until then, flip it 180 degree from how you have shown. So the face that is currently highest Z height is now on the bed. And correct, you will need supports for this model.

On this topic though, I would probably recommend using one of the other designs instead of the one with the filament sensor. If you are trying to use this with ERCF, the newer version of the software no longer needs a filament sensor below the extruder. I am running this software, and prefer sensorless to a dedicated filament sensor. [You can read about it more here.](https://github.com/moggieuk/ERCF-Software-V3)
